<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfbmkjh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfbmkjh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBfbmkjh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBfbmkjh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBfbmkjh\srcDevDebugProjectContainer([
    'container.build_hash' => 'Bfbmkjh',
    'container.build_id' => '87bb5f41',
    'container.build_time' => 1586602313,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfbmkjh');
