<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxnfvc4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxnfvc4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxnfvc4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxnfvc4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKxnfvc4\srcDevDebugProjectContainer([
    'container.build_hash' => 'Kxnfvc4',
    'container.build_id' => 'fd7a9d88',
    'container.build_time' => 1586607928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxnfvc4');
